units:
  kx: 17 
  ky: 17
  px: kx
  py: ky
  kxo: 0.5 * kx
  kyo: 0.5 * ky

  cfx_x_1u: 16.5
  cfx_x_1_5u: 26
  cfx_x_1_5u_span: 13.25 + kx/2
  cfx_x_space:  54.5
  # PG1232 plate cutout FIXME regular chic
  plate_kx: 13.6
  plate_ky: 12.6

  # Font units
  font_x: 1
  font_y: 1
  font_xo: 0.5 font_x
  font_yo: 0.5 * font_y

  # Nice Nano
  # The nice nano footprint's center doesn't account
  # for the 2.54mm "overhang" of the PCB beyond the pins.
  mcu_overhang_y: 2.54
  mcu_spacing_x: 2.72
  mcu_x: 17.78 + mcu_spacing_x
  mcu_y: 30.48 + mcu_overhang_y
  mcu_xo: 0.5 * mcu_x
  mcu_yo: 0.5 * mcu_y + 0.5 * mcu_overhang_y

  # Nice!View display
  disp_x: 14
  disp_y: 36
  disp_jumper_y: 2.6
  disp_xo: 0.5 * disp_x
  disp_yo: 0.5 * disp_y

  # Battery Connector
  batc_x: 4.3
  batc_y: 4.6
  batc_xo: 0.5 * batc_x
  batc_yo: 0.5 * batc_y

  # Battery Pads
  batp_x: 3.75
  batp_y: 2.5
  batp_xo: 0.5 * batp_x
  batp_yo: 0.5 * batp_y

  # Power Switch
  sw_power_x: 3.1
  sw_power_y: 8.3
  sw_power_xo: 0.5 * sw_power_x
  sw_power_yo: 0.5 * sw_power_y

  # Reset Switch
  sw_reset_x: 3.4
  sw_reset_y: 5
  sw_reset_xo: 0.5 * sw_reset_x
  sw_reset_yo: 0.5 * sw_reset_y

points:
  key:
    padding: ky
    spread: kx
    width: cfx_x_1u
    height: cfx_x_1u
  zones:
    matrix:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [35, -100]
      key.tags: key
      columns:
        left:
          key:
            spread: cfx_x_1_5u_span
            width: cfx_x_1_5u
            asym: left
            column_net: C0
            tags: [key, 1_5u]
        q:
          key:
            spread: cfx_x_1_5u_span
            column_net: C1
        w:
          key.column_net: C2
        e:
          key.column_net: C3
        r:
          key.column_net: C4
        t:
          key.column_net: C5
        enter:
          key:
            column_net: C6
            spread: cfx_x_1_5u_span
            width: cfx_x_1_5u
            tags: [key, 1_5u]
      rows:
        bottom:
          row_net: R4
        home:
          row_net: R3
        top:
          row_net: R2
        num:
          row_net: R1
        f:
          row_net: R0

    leftcluster:
      key:
        spread: cfx_x_1_5u+0.5
        width: cfx_x_1_5u
        asym: left
        tags: [key, 1_5u]
      anchor:
        ref: matrix_left_bottom
        shift: [0, -2ky]
      columns:
        one:
          key.column_net: C0
        two:
          #key.width: 21.50
          key.column_net: C1
        three:
          key.column_net: C2
      rows:
        down:
          row_net: R6
        up:
          row_net: R5
    rightcluster:
      key:
        asym: right
        tags: key
      anchor:
        ref: matrix_q_bottom
        shift: [-1 kx, -2ky]
      columns:
        one:
          key.column_net: C0
        two:
          key.column_net: C1
        three:
          key.column_net: C2
      rows:
        down:
          row_net: R6
        up:
          row_net: R5

        
    spaces:
      key.tags: key
      anchor:
        ref: matrix_q_bottom
        shift: [2kx, -1ky]
      columns:
        alt:
          key:
            asym: right
            column_net: C3
        space:
          key:
            width: cfx_x_space
            spread: 41.5
            column_net: C4
            tags: [key, space]
      rows:
        space:
          row_net: R5
    rightsym:
      anchor:
        ref: matrix_q_bottom
        shift: [-kx, 0]
      key:
        asym: right
        tags: key
      columns:
        sym:
          key.column_net: C0
       
      rows:
        bottom:
          row_net: R4
        home:
          row_net: R3
        top:
          row_net: R2
        num:
          row_net: R1
        f:
          row_net: R0
    right:
      anchor:
        ref: rightsym_sym_bottom
        shift: [-cfx_x_1_5u_span, -2ky]
      key:
        asym: right
        spread: cfx_x_1_5u_span
        width: cfx_x_1_5u
        tags: [key, 1_5u]
      columns:
        sym:
          key.column_net: C7
      rows:
        ctl_down:
          row_net: R6
        ctl_up:
          row_net: R5
        bottom:
          row_net: R4
        home:
          row_net: R3
        top:
          row_net: R2
        num:
          row_net: R1
        f:
          row_net: R0

    #  Controller
    #
    controller:
      anchor:
        ref: matrix_enter_f
        shift: [cfx_x_1_5u/2 + mcu_xo +1, kyo -2.25 - mcu_yo]
      key:
        name: mcu
        width: mcu_x
        height: mcu_y

  mirror: &mirror
    ref: matrix_enter_f
    distance: 100
outlines:
  _keys:
    - what: rectangle
      where: [[key, -space]]
      size: [plate_kx/2, plate_ky/2]
  _enters:
    - what: rectangle
      where: [[key, enter]]
      size: [plate_ky/2, plate_kx/2]
  _spaces:
    - what: rectangle
      where: [[key, space]]
      size: [plate_kx/2, plate_ky/2]

  _outline_left:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_left_f
          shift: [-cfx_x_1_5u/2 - 0.25, ky * 0.5]
        - ref: matrix_enter_f
          shift: [cfx_x_1_5u/2 + 0.25, ky * 0.5]
        - ref: matrix_enter_bottom
          shift: [cfx_x_1_5u/2 + 0.25, -ky * 1.5]
        - ref: leftcluster_three_down
          shift: [cfx_x_1_5u/2 + 0.25, ky * 0.5]
        - ref: leftcluster_three_down
          shift: [cfx_x_1_5u/2 + 0.25, -ky * 0.5]
        - ref: leftcluster_one_down
          shift: [-cfx_x_1_5u/2 - 0.25, -ky * 0.5]

  _outline_right:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_right_sym_f
          shift: [-cfx_x_1_5u/2 - 0.25, ky * 0.5]
        - ref: mirror_matrix_enter_f
          shift: [cfx_x_1_5u/2 + 0.25, ky * 0.5]
        - ref: mirror_matrix_enter_bottom
          shift: [cfx_x_1_5u/2 + 0.25, -ky * 1.5]
        - ref: mirror_rightcluster_three_down
          shift: [kx/2, ky * 0.5]
        - ref: mirror_rightcluster_three_down
          shift: [kx/2, -ky * 0.5]
        - ref: mirror_right_sym_ctl_down
          shift: [-cfx_x_1_5u/2 - 0.25, -ky * 0.5]
  
  _mcuears:
    - what: rectangle
      size: [mcu_x +10, 6ky]
      fillet: 2

  pcb_left:
    - name: _outline_left
    - operation: add
      name: _mcuears
      where:
        ref: matrix_enter_f
        shift: [0.75 * kx + mcu_x/2 -5, -2.5ky]

  pcb_right:
    - name: _outline_right
    - operation: add
      name: _mcuears
      where:
        ref: mirror_matrix_enter_f
        shift: [0.75 * kx + mcu_x/2 -5, -2.5ky]

  topleft:
    - name: _outline_left
    - operation: subtract
      name: _keys
    - operation: subtract
      name: _spaces


  topright:
    - name: _outline_right
    - operation: subtract
      name: _keys
    - operation: subtract
      name: _spaces



  bottomright:
    - name: pcb_right

  bottomleft:
    - name: pcb_left

  # Combination preview showing outline and keys.
  combined:
    - name: topleft
    - operation: stack
      name: topright


pcbs:
  left:
    outlines:
      left:
        outline: pcb_left
    footprints:
      choc:
        what: choc
        where:
          - [/^matrix_.*/, key, -1_5u]
          - [/^spaces_.*/, key, -space]
        params:
          keycaps: true
          reverse: false
          hotswap: true
          keycaps_x: 16.5
          keycaps_y: 16.5
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_1_5u:
        what: choc
        where:
          - [/^matrix_.*/, 1_5u]
          - /leftcluster_.*/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{colrow}}"
          to: "{{column_net}}"
          keycaps_x: cfx_x_1_5u
          keycaps_y: 16.5
      choc_space:
        what: choc
        where: 
          - [/^spaces_.*/, key, -1_5u, space]

        params:
          keycaps: true
          reverse: false
          hotswap: true
          keycaps_x: cfx_x_space

          keycaps_y: 16.5
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: diode
        where:
          - /^matrix_.*/
          - /leftcluster_.*/
          - /^spaces_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          tht: false # No through hole
          side: B # Bottom only
        adjust:
          shift: [-1.4, -6]
          rotate: 180
      # Controller Area
      promicro:
        what: promicro
        params:
          # Pin Assignments (Controller on top facing down)
          # Right Side
          P0: "DPD" # Display Data
          P1: "DPC" # Display Clock
          # GND
          # GND
          P2: "DPE" # Display CS (nice!view only) FIXME? ZPM default?
          P3: "R1" # Row
          P4: "R2" # Row
          P5: "R3" # Row
          P6: "R4" # Row
          P7: "R5" # Row
          P8: "R6" # Row
          P9: "R7" # Row

          # Left Side
          RAW: "BAT_P" # Battery Pos
          # GND       # Ground / Battery Neg
          # RST       # Reset pin
          # VCC       # External Power
          P21: "C0" # Column
          P20: "C1" # Column
          P19: "C2" # Column
          P18: "C3" # Column
          P15: "C4" # Column
          P14: "C5" # Column
          P16: "C6" # Column
#          P10: "F10" # Free

        where:
          ref: mcu
          shift: [0, 0]
          rotate: -90
      display:
        what: nice_view
        params:
          reverse: false
          MOSI: DPD
          SCK: DPC
          CS: DPE
          show_labels: false
          jumpers_at_bottom: false
        where:
          ref: mcu
          shift: [0, -1] # Move the display down a bit to be sure the cable fits between the headers
      pads_bat:
        what: jstph
        params:
          pos: BAT_P
          neg: GND
        where:
          ref: mcu
          shift: [-batc_x, -mcu_y/2 - 5]
          #rotate: 270
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mcu
          shift: [batc_x, -mcu_y/2 - 8]

  right:
    outlines:
      right:
        outline: pcb_right
    footprints:
      choc:
        what: choc
        where:
          - [/^mirror.*/, key, -1_5u, -space]
          - /rightcluster_.*/
        
        params:
          keycaps: true
          reverse: false
          hotswap: true
          keycaps_x: 16.5
          keycaps_y: 16.5
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_1_5u:
        what: choc
        where: 
          - [/^mirror.*/, 1_5u]
          - [/rightcluster_.*/, 1_5u]
          - [/right.*/, 1_5u]
        params:
          keycaps: true
          reverse: false
          hotswap: true
          keycaps_x: cfx_x_1_5u
          keycaps_y: 16.5
          from: "{{colrow}}"
          to: "{{column_net}}"
      choc_space:
        what: choc
        where: 
          - [/^mirror.*/, key, -1_5u, space]
        params:
          keycaps: true
          reverse: false
          hotswap: true
          keycaps_x: cfx_x_space
          keycaps_y: 16.5
          from: "{{colrow}}"
          to: "{{column_net}}"
      diode:
        what: diode
        where:
          - [/^mirror.*/, key]
          - /rightcluster_.*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          tht: false # No through hole
          side: B # Bottom only
        adjust:
          shift: [1.4, -6]
          rotate: 180
      # Controller Area
      promicro:
        what: promicro
        params:
          # Pin Assignments (Controller on top facing down)
          # Right Side
          P0: "DPD" # Display Data
          P1: "DPC" # Display Clock
          # GND
          # GND
          P2: "DPE" # Display CS (nice!view only) FIXME? ZPM default?
          P3: "R1" # Row
          P4: "R2" # Row
          P5: "R3" # Row
          P6: "R4" # Row
          P7: "R5" # Row
          P8: "R6" # Row
          P9: "R7" # Row

          # Left Side
          RAW: "BAT_P" # Battery Pos
          # GND       # Ground / Battery Neg
          # RST       # Reset pin
          # VCC       # External Power
          P21: "C0" # Column
          P20: "C1" # Column
          P19: "C2" # Column
          P18: "C3" # Column
          P15: "C4" # Column
          P14: "C5" # Column
          P16: "C6" # Column
#          P10: "C7" # Column

        where:
          ref: mirror_mcu
          shift: [0, 0]
          rotate: 90

      display:
        what: nice_view
        params:
          reverse: false
          MOSI: DPD
          SCK: DPC
          CS: DPE
          show_labels: false
          jumpers_at_bottom: false
        where:
          ref: mirror_mcu
          shift: [0, -1] # Move the display down a bit to be sure the cable fits between the headers
      pads_bat:
        what: jstph
        params:
          pos: BAT_P
          neg: GND
        where:
          ref: mirror_mcu
          shift: [-batc_x, -mcu_y/2 - 5]
          #rotate: 270
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: mirror_mcu
          shift: [batc_x, -mcu_y/2 - 8]
